"""Shared data models and protocols used across Hamster packages."""

from hamster.shared.models import (
    ActionFailure,
    ActionType,
    ApplicationRecord,
    ApplicationStatus,
    ApplyResult,
    Education,
    ElementType,
    Experience,
    FillPlan,
    JobListing,
    JobSourceName,
    PageAction,
    PageAnalysis,
    PageDOM,
    PageElement,
    PageType,
    SearchQuery,
    UserProfile,
)
from hamster.shared.protocols import (
    Applicator,
    FormMapper,
    JobSource,
    LLMClient,
    PageAnalyzer,
    ProfileStorage,
    PromptBuilder,
)

__all__ = [
    # models
    "ActionFailure",
    "ActionType",
    "ApplicationRecord",
    "ApplicationStatus",
    "ApplyResult",
    "Education",
    "ElementType",
    "Experience",
    "FillPlan",
    "JobListing",
    "JobSourceName",
    "PageAction",
    "PageAnalysis",
    "PageDOM",
    "PageElement",
    "PageType",
    "SearchQuery",
    "UserProfile",
    # protocols
    "Applicator",
    "FormMapper",
    "JobSource",
    "LLMClient",
    "PageAnalyzer",
    "ProfileStorage",
    "PromptBuilder",
]
